import { NextResponse } from "next/server";

// Mock server store data
const mockStoreServers = [
  {
    serverId: "filesystem-official",
    name: "Filesystem Server",
    description: "Official MCP server for filesystem operations",
    category: "filesystem",
    version: "1.0.0",
    author: "Anthropic",
    rating: 4.8,
    downloads: 15420,
    verified: true,
    tags: ["files", "io", "official"],
    readme: "A robust filesystem server implementation for MCP. Supports reading, writing, and directory operations with proper error handling.",
    lastUpdated: new Date("2024-10-15"),
    repository: "https://github.com/modelcontextprotocol/servers",
    homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
  },
  {
    serverId: "git-official",
    name: "Git Server",
    description: "Official Git operations server for version control",
    category: "git",
    version: "1.2.0",
    author: "Anthropic",
    rating: 4.7,
    downloads: 12350,
    verified: true,
    tags: ["git", "version-control", "official"],
    readme: "Integrate Git operations directly into your MCP client. Supports commit, push, pull, branch management, and more.",
    lastUpdated: new Date("2024-10-20"),
    repository: "https://github.com/modelcontextprotocol/servers",
    homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/git",
  },
  {
    serverId: "github-community",
    name: "GitHub Integration",
    description: "Community-maintained GitHub repository integration",
    category: "github",
    version: "2.1.0",
    author: "MCP Community",
    rating: 4.5,
    downloads: 8930,
    verified: true,
    tags: ["github", "api", "repository"],
    readme: "Connect to GitHub repositories, manage issues, pull requests, and collaborate with your team directly through MCP.",
    lastUpdated: new Date("2024-10-25"),
    repository: "https://github.com/mcp-community/mcp-github",
    homepage: "https://github.com/mcp-community/mcp-github",
  },
  {
    serverId: "postgres-community",
    name: "PostgreSQL Server",
    description: "Community PostgreSQL database operations",
    category: "database",
    version: "1.5.2",
    author: "Database Team",
    rating: 4.3,
    downloads: 5670,
    verified: true,
    tags: ["database", "postgresql", "sql"],
    readme: "Execute SQL queries and manage PostgreSQL databases. Includes query builder and result formatting.",
    lastUpdated: new Date("2024-10-18"),
    repository: "https://github.com/mcp-community/mcp-postgres",
    homepage: "https://github.com/mcp-community/mcp-postgres",
  },
  {
    serverId: "brave-search",
    name: "Brave Search",
    description: "Web search using Brave Search API",
    category: "web",
    version: "0.3.0",
    author: "Brave Software",
    rating: 4.6,
    downloads: 7890,
    verified: true,
    tags: ["search", "web", "api"],
    readme: "Private, fast web search for your AI assistant. Get relevant search results with privacy protection.",
    lastUpdated: new Date("2024-10-22"),
    repository: "https://github.com/brave/brave-mcp-server",
    homepage: "https://github.com/brave/brave-mcp-server",
  },
  {
    serverId: "memory-ai",
    name: "Memory & Context",
    description: "AI-powered memory and context management",
    category: "memory",
    version: "0.2.5",
    author: "AI Research Lab",
    rating: 4.9,
    downloads: 11200,
    verified: true,
    tags: ["memory", "context", "ai"],
    readme: "Intelligent context management for AI assistants. Learn from interactions and maintain contextual awareness.",
    lastUpdated: new Date("2024-10-28"),
    repository: "https://github.com/ai-research/mcp-memory",
    homepage: "https://github.com/ai-research/mcp-memory",
  },
  {
    serverId: "slack-team",
    name: "Slack Integration",
    description: "Team communication through Slack",
    category: "custom",
    version: "1.0.0",
    author: "Team Tools Co",
    rating: 4.2,
    downloads: 4320,
    verified: false,
    tags: ["slack", "chat", "team"],
    readme: "Send messages, create channels, and manage Slack workspace directly from your MCP client.",
    lastUpdated: new Date("2024-10-10"),
    repository: "https://github.com/team-tools/mcp-slack",
    homepage: "https://github.com/team-tools/mcp-slack",
  },
  {
    serverId: "redis-cache",
    name: "Redis Cache",
    description: "High-performance caching with Redis",
    category: "database",
    version: "0.8.0",
    author: "Cache Solutions",
    rating: 4.4,
    downloads: 3450,
    verified: true,
    tags: ["cache", "redis", "performance"],
    readme: "Lightning-fast caching and data storage using Redis. Perfect for session management and temporary data.",
    lastUpdated: new Date("2024-10-05"),
    repository: "https://github.com/cache-solutions/mcp-redis",
    homepage: "https://github.com/cache-solutions/mcp-redis",
  },
];

export async function GET() {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500));

  return NextResponse.json(mockStoreServers);
}
